##### Plugins #####
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-resurrect'
set -g @plugin 'christoomey/vim-tmux-navigator'

##### Shell #####
set-option -g default-shell "/bin/zsh"

##### Prefix #####
unbind C-b
set-option -g prefix C-f
bind-key C-f send-prefix

##### Mouse #####
set-option -g mouse on
bind m set -g mouse on \; display-message "Mouse: ON"
bind M set -g mouse off \; display-message "Mouse: OFF"

##### Copy mode #####
setw -g mode-keys vi
bind v copy-mode

# Start normal character selection
bind-key -T copy-mode-vi v send -X begin-selection

# Start line selection like Vim Shift+v
bind-key -T copy-mode-vi V send -X select-line

# Optional: make Space select whole line instead of character selection
bind-key -T copy-mode-vi Space send -X select-line

# Copy selected text to macOS clipboard
bind-key -T copy-mode-vi y send -X copy-pipe-and-cancel "pbcopy"

# Copy whole current line to macOS clipboard
bind-key -T copy-mode-vi Y send -X select-line \; send -X copy-pipe-and-cancel "pbcopy"

##### Windows / panes #####
unbind c
bind c new-window -c ~

unbind '"'
unbind %
bind '"' split-window -v -c ~
bind % split-window -h -c ~
bind | split-window -h -c ~
bind - split-window -v -c ~

##### Reload config #####
bind r source-file ~/.tmux.conf \; display-message "tmux config reloaded"

##### Window names #####
set-option -g allow-rename off

##### Resize / zoom pane #####
bind-key > resize-pane -Z \; display-message "Zoom zoom zoom"

##### Resize / zoom pane #####
bind-key > resize-pane -Z \; display-message "Zoom zoom zoom"
bind -r H resize-pane -L 5
bind -r L resize-pane -R 5
bind -r K resize-pane -U 5
bind -r J resize-pane -D 5

##### Terminal / colors #####
set -g default-terminal "tmux-256color"
set-environment -gu TERM
set -g focus-events on
set-option -ga terminal-overrides ",xterm-256color:Tc"
set-option -ga terminal-overrides ",tmux-256color:Tc"

##### Dracula theme #####
set -g @dracula-show-fahrenheit false
set -g @dracula-plugins "cpu-usage ram-usage time"
set -g @dracula-show-powerline true
set -g @dracula-show-left-icon empty
set -g @dracula-show-timezone false
set -g @dracula-border-contrast true
set -g @dracula-show-left-sep 
set -g @dracula-background-color "#002b36"
set -g @dracula-show-right-sep 
set -g @dracula-show-flags true

run-shell ~/.tmux/plugins/tmux-dracula/dracula.tmux

##### Optional: pane scrollbars #####
set -g pane-scrollbars on

##### TPM init. Keep this at the very bottom. #####
run '~/.tmux/plugins/tpm/tpm'
